=== techlabsms/ms-wt-21-11-sharedHolidayHomes/server/schemas/house.schema.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "name": {
      "type": "string"
    },
    "priceInEuro": {
      "type": "number"
    },
    "areaInSqM": {
      "type": "number"
    },
    "roomCount": {
      "type": "number"
    },
    "totalShares": {
      "type": "number"
    },
    "availableShares": {
      "type": "number"
    },
    "specials": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "images": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "address": {
      "type": "object",
      "properties": {
        "street": {
          "type": "string"
        },
        "houseNumber": {
          "type": "number"
        },
        "zipCode": {
          "type": "string"
        },
        "locality": {
          "type": "string"
        }
      }
    }
  },
  "required": [
    "name",
    "priceInEuro",
    "areaInSqM",
    "roomCount",
    "totalShares",
    "availableShares",
    "specials",
    "images",
    "address"
  ]
}

=== techlabsms/ms-wt-21-11-sharedHolidayHomes/server/mock.json
[
  {
    "name": "house1",
    "priceInEuro": 450000,
    "areaInSqM": 105,
    "roomCount": 4,
    "totalShares": 3,
    "availableShares": 1,
    "specials": ["forest", "balcony", "inVillage"],
    "images": [
      "https://cdn.pixabay.com/photo/2017/08/18/09/37/holiday-home-2654349_960_720.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/e/e4/Rayynor_Silva_Holiday_Home_The_White_Lotus_in_Bolgoda_Image_13.jpg"
    ],
    "address": {
      "street": "Waldseeweg",
      "houseNumber": 25,
      "zipCode": "77716",
      "locality": "Haslach im Kinzigtal"
    }
  },
  {
    "name": "house2",
    "priceInEuro": 1000000,
    "areaInSqM": 132.5,
    "roomCount": 5,
    "totalShares": 6,
    "availableShares": 5,
    "specials": ["pool", "terrace", "inTown"],
    "images": [
      "https://cdn.fertighauswelt.de/4e3e37329a9a711e50f0040ff52032905d0d0f16/fingerhaus-einfamilienhaus-pool-1902x1436-340x257.jpg",
      "https://cdn.fertighauswelt.de/9673c2e1662fb0a35c0889876fe1a0111dfc0855/fingerhaus-einfamilienhaus-lage-510x340.jpg",
      "https://cdn.fertighauswelt.de/5eb8c2a8029501097f88cd4921de0dca78176f85/fingerhaus-einfamilienhaus-puristisch.jpg",
      "https://cdn.fertighauswelt.de/91dae566a134996bf58f5dfc40540e55a72c5d22/fingerhaus-einfamilienhaus-treppe-1653x1268-510x391.jpg",
      "https://cdn.fertighauswelt.de/a3d4f63352334ebc2657dc982ebf14418181b4a8/fingerhaus-einfamilienhaus-kinderzimmer-510x340.jpg",
      "https://cdn.fertighauswelt.de/26f9ece9f1ec9a3f4ef52e52c80c0de034da0588/fingerhaus-einfamilienhaus-kinderzimmer-2-510x340.jpg"
    ],
    "address": {
      "street": "Schwedenstraße",
      "houseNumber": 50,
      "zipCode": "80805",
      "locality": "München"
    }
  }
]
